### PR TITLE
Fixing Video Square problem in tele desktop.

### PR DESCRIPTION
**Pull request by WeebTime**
https://telegra.ph/file/b0b1afdb7e8f2ef680dfc.jpg

Now - https://telegra.ph/file/f7f315913a006479f8e04.jpg

### CODE REVIEW

**Comment by yash-dk** [comment]
Thanks For PR will review and push

**Comment by yash-dk** [comment]
Can you PR on beta branch?

**Comment by yourtulloh** [comment]
> Thanks For PR will review and push

Yes its fixed now

**Comment by WeebTime** [comment]
> Can you PR on beta branch?

sure

**Pull request closed without merging**
