### PR TITLE
fixed grammatical mistakes and add Telegram button channel link of ttk on homepaage

### PR DESCRIPTION
**Pull request by AmirulAndalib**
fixed grammatical mistakes and add Telegram button channel link of ttk on homepaage

### CODE REVIEW

**Comment by AmirulAndalib** [comment]
# i recently added a nice beautiful file selection ui thanks to @bipuldey19-Telegram and Slam Mirror Bot for this Mod.....

Screenshot (3105)
Screenshot (3104)


## Please Make Sure to check it out...

**Comment by dishapatel010** [comment]
Hmmm :wrench:

**Comment by yash-dk** [comment]
looks nice will test and merge on weekend... Thanks for PR

**Comment by AmirulAndalib** [comment]
Thanks 👍

**Comment by gitenvx** [comment]
> Thanks

You forget to say sorry to dev

**Comment by AmirulAndalib** [comment]
> > Thanks
> 
> You forget to say sorry to dev

Yes I am Sorry For Saying bad words Previously On A Repository 😞

**Comment by yash-dk** [comment]
> > > Thanks
> > 
> > 
> > You forget to say sorry to dev
> 
> Yes I am Sorry For Saying bad words Previously On A Repository 😞

No Issues GG 👍 👍

**Pull request merged**
